### ISSUE TITLE
Querier contract error: Generic error: Error decoding bech32

### ISSUE THREAD

**Issue by JohnScience** [CosmWasm/cw-multi-test#165]
I was writing a test based on <https://book.cosmwasm.com/basics/funds.html>.

Original:

```rs
#[cfg(test)]
mod tests {
    #[test]
    fn donations() {
        let mut app = App::new(|router, _, storage| {
            router
                .bank
                .init_balance(storage, &Addr::unchecked("user"), coins(5, "eth"))
                .unwrap()
        });

        let code = ContractWrapper::new(execute, instantiate, query);
        let code_id = app.store_code(Box::new(code));

        let addr = app
            .instantiate_contract(
                code_id,
                Addr::unchecked("owner"),
                &InstantiateMsg {
                    admins: vec!["admin1".to_owned(), "admin2".to_owned()],
                    donation_denom: "eth".to_owned(),
                },
                &[],
                "Contract",
                None,
            )
            .unwrap();

        app.execute_contract(
            Addr::unchecked("user"),
            addr.clone(),
            &ExecuteMsg::Donate {},
            &coins(5, "eth"),
        )
        .unwrap();

        assert_eq!(
            app.wrap()
                .query_balance("user", "eth")
                .unwrap()
                .amount
                .u128(),
            0
        );

        assert_eq!(
            app.wrap()
                .query_balance(&addr, "eth")
                .unwrap()
                .amount
                .u128(),
            1
        );

        assert_eq!(
            app.wrap()
                .query_balance("admin1", "eth")
                .unwrap()
                .amount
                .u128(),
            2
        );

        assert_eq!(
            app.wrap()
                .query_balance("admin2", "eth")
                .unwrap()
                .amount
                .u128(),
            2
        );
    }
}
```

Minimal Reproducible Example (MRE):

```rs
#[cfg(test)]
mod tests {
    use cosmwasm_std::{coins, Addr};
    use cw_multi_test::App;

    #[test]
    fn multitest() {
        let app = App::new(|router, _, storage| {
            router
                .bank
                .init_balance(storage, &Addr::unchecked("user"), coins(5, "eth"))
                .unwrap()
        });
        let balance = app
            .wrap()
            .query_balance(&Addr::unchecked("user"), "eth")
            // panic happens here
            .unwrap()
            .amount
            .u128();
        assert_eq!(balance, 5);
    }
}
```

However, I'm getting 

```
---- contract::tests::multitest stdout ----
thread 'contract::tests::multitest' panicked at src\contract.rs:200:14:
called `Result::unwrap()` on an `Err` value: GenericErr { msg: "Querier contract error: Generic error: Error decoding bech32", backtrace: Backtrace [{ fn: "std::backtrace_rs::backtrace::dbghelp::trace", file: "/rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs", line: 131 }, { fn: "std::backtrace_rs::backtrace::trace_unsynchronized", file: "/rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library\std\src\..\..\backtrace\src\backtrace\mod.rs", line: 66 }, { fn: "std::backtrace::Backtrace::create", file: "/rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library\std\src\backtrace.rs", line: 331 }, { fn: "std::backtrace::Backtrace::capture", file: "/rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library\std\src\backtrace.rs", line: 296 }, { fn: "cosmwasm_std::errors::backtrace::BT::capture", file: "C:\Users\USER\.cargo\registry\src\index.crates.io-6f17d22bba15001f\cosmwasm-std-2.0.1\src\errors\backtrace.rs", line: 19 }, { fn: "enum2$<cosmwasm_std::errors::std_error::StdError>::generic_err<alloc::string::String>", file: "C:\Users\USER\.cargo\registry\src\index.crates.io-6f17d22bba15001f\cosmwasm-std-2.0.1\src\errors\std_error.rs", line: 109 }, { fn: "cosmwasm_std::traits::QuerierWrapper<cosmwasm_std::results::empty::Empty>::query<cosmwasm_std::results::empty::Empty,cosmwasm_std::query::bank::BalanceResponse>", file: "C:\Users\USER\.cargo\registry\src\index.crates.io-6f17d22bba15001f\cosmwasm-std-2.0.1\src\traits.rs", line: 251 }, { fn: "cosmwasm_std::traits::QuerierWrapper<cosmwasm_std::results::empty::Empty>::query_balance<cosmwasm_std::results::empty::Empty,ref$<str$>,ref$<str$> >", file: "C:\Users\USER\.cargo\registry\src\index.crates.io-6f17d22bba15001f\cosmwasm-std-2.0.1\src\traits.rs", line: 278 }, { fn: "donations_contract::contract::tests::multitest", file: ".\src\contract.rs", line: 197 }, { fn: "donations_contract::contract::tests::multitest::closure$0", file: ".\src\contract.rs", line: 190 }, { fn: "core::ops::function::FnOnce::call_once<donations_contract::contract::tests::multitest::closure_env$0,tuple$<> >", file: "/rustc/aedd173a2c086e558c2b66d3743b344f977621a7\library\core\src\ops\function.rs", line: 250 }, { fn: "core::ops::function::FnOnce::call_once", file: "/rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library\core\src\ops\function.rs", line: 250 }, { fn: "test::__rust_begin_short_backtrace<enum2$<core::result::Result<tuple$<>,alloc::string::String> >,enum2$<core::result::Result<tuple$<>,alloc::string::String> > (*)()>", file: "/rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library\test\src\lib.rs", line: 621 }, { fn: "test::run_test_in_process::closure$0", file: "/rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library\test\src\lib.rs", line: 644 }, { fn: "core::panic::unwind_safe::impl$23::call_once", file: "/rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library\core\src\panic\unwind_safe.rs", line: 272 }, { fn: "std::panicking::try::do_call", file: "/rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library\std\src\panicking.rs", line: 554 }, { fn: "std::panicking::try", file: "/rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library\std\src\panicking.rs", line: 518 }, { fn: "std::panic::catch_unwind", file: "/rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library\std\src\panic.rs", line: 142 }, { fn: "test::run_test_in_process", file: "/rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library\test\src\lib.rs", line: 644 }, { fn: "test::run_test::closure$0", file: "/rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library\test\src\lib.rs", line: 567 }, { fn: "test::run_test::closure$1", file: "/rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library\test\src\lib.rs", line: 595 }, { fn: "std::sys_common::backtrace::__rust_begin_short_backtrace<test::run_test::closure_env$1,tuple$<> >", file: "/rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library\std\src\sys_common\backtrace.rs", line: 155 }, { fn: "std::thread::impl$0::spawn_unchecked_::closure$1::closure$0", file: "/rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library\std\src\thread\mod.rs", line: 529 }, { fn: "core::panic::unwind_safe::impl$23::call_once", file: "/rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library\core\src\panic\unwind_safe.rs", line: 272 }, { fn: "std::panicking::try::do_call", file: "/rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library\std\src\panicking.rs", line: 554 }, { fn: "std::panicking::try", file: "/rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library\std\src\panicking.rs", line: 518 }, { fn: "std::panic::catch_unwind", file: "/rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library\std\src\panic.rs", line: 142 }, { fn: "std::thread::impl$0::spawn_unchecked_::closure$1", file: "/rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library\std\src\thread\mod.rs", line: 528 }, { fn: "core::ops::function::FnOnce::call_once<std::thread::impl$0::spawn_unchecked_::closure_env$1<test::run_test::closure_env$1,tuple$<> >,tuple$<> >", file: "/rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library\core\src\ops\function.rs", line: 250 }, { fn: "std::sys::pal::windows::thread::impl$0::new::thread_start", file: "/rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library\std\src\sys\pal\windows\thread.rs", line: 58 }, { fn: "BaseThreadInitThunk" }, { fn: "RtlUserThreadStart" }] }
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library\std\src\panicking.rs:647
   1: core::panicking::panic_fmt
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library\core\src\panicking.rs:72
   2: core::result::unwrap_failed
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library\core\src\result.rs:1649
   3: enum2$<core::result::Result<cosmwasm_std::coin::Coin,enum2$<cosmwasm_std::errors::std_error::StdError> > >::unwrap
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7\library\core\src\result.rs:1073
   4: donations_contract::contract::tests::multitest
             at .\src\contract.rs:197
   5: donations_contract::contract::tests::multitest::closure$0
             at .\src\contract.rs:190
   6: core::ops::function::FnOnce::call_once<donations_contract::contract::tests::multitest::closure_env$0,tuple$<> >
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7\library\core\src\ops\function.rs:250
   7: core::ops::function::FnOnce::call_once
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library\core\src\ops\function.rs:250
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by JohnScience** [comment]
It looks like the problem is that in the implementation of `Module` for `BankKeeper`, the address in the `BankQuery::Balance` request gets validated:

```
impl Module for BankKeeper {
    type ExecT = BankMsg;
    type QueryT = BankQuery;
    type SudoT = BankSudo;

   // ...

  fn query(
        &self,
        api: &dyn Api,
        storage: &dyn Storage,
        _querier: &dyn Querier,
        _block: &BlockInfo,
        request: BankQuery,
    ) -> AnyResult<Binary> {
        let bank_storage = prefixed_read(storage, NAMESPACE_BANK);
        match request {
            BankQuery::AllBalances { address } => {
                let address = api.addr_validate(&address)?;
                let amount = self.get_balance(&bank_storage, &address)?;
                let res = AllBalanceResponse::new(amount);
                to_json_binary(&res).map_err(Into::into)
            }
            BankQuery::Balance { address, denom } => {
                let address = api.addr_validate(&address)?;
                let all_amounts = self.get_balance(&bank_storage, &address)?;
                let amount = all_amounts
                    .into_iter()
                    .find(|c| c.denom == denom)
                    .unwrap_or_else(|| coin(0, denom));
                let res = BalanceResponse::new(amount);
                to_json_binary(&res).map_err(Into::into)
            }
            BankQuery::Supply { denom } => {
                let amount = self.get_supply(&bank_storage, denom)?;
                let res = SupplyResponse::new(amount);
                to_json_binary(&res).map_err(Into::into)
            }
            BankQuery::DenomMetadata { denom } => {
                let meta = DENOM_METADATA.may_load(storage, denom)?.unwrap_or_default();
                let res = DenomMetadataResponse::new(meta);
                to_json_binary(&res).map_err(Into::into)
            }
            BankQuery::AllDenomMetadata { pagination: _ } => {
                let mut metadata = vec![];
                for key in DENOM_METADATA.keys(storage, None, None, Order::Ascending) {
                    metadata.push(DENOM_METADATA.may_load(storage, key?)?.unwrap_or_default());
                }
                let res = AllDenomMetadataResponse::new(metadata, None);
                to_json_binary(&res).map_err(Into::into)
            }
            other => unimplemented!("bank query: {other:?}"),
        }
    }
}
```

**Comment by JohnScience** [comment]
I just checked the `git blame` and it looks like the implementation of `Module` for `BankKeeper` always validated the address.

**Comment by JohnScience** [comment]
I tried to ask this question in the `#support` channel of the Osmosis Discord sever but I got a time out. Here's a copy of the message that I failed to sent to any of the admins:

```
Hi, I just found out that I got a time out on Osmosis server. However, I sent only 2 harmless messages (both in the #testnet-discussions):

A request to send me money on the testnet (because the testnet was down and, according to https://docs.osmosis.zone/cosmwasm/testnet/cosmwasm-deployment/#discord-faucet, there used to be a faucet channel, so I sent it to `#testnet-discussions` channel instead).

A message where I stated that I started learning how to run the testnet locally (with a link, https://medium.com/@vishalpotpelliwar123/deploying-cosmwasm-smart-contract-on-local-testnet-c6a3d973865c).

I never was mentioned, so I wonder if there was a mistake.
```

**Comment by JohnScience** [comment]
This failed too:
```
#[cfg(test)]
mod tests {
 // ...
    #[test]
    fn multitest() {
        let mut app = App::default();

        let user_addr = app.api().addr_make("user");

        app.init_modules(|router, _, storage| {
            router
                .bank
                .init_balance(storage, &user_addr, coins(5, "eth"))
                .unwrap();
        });

        let balance = app
            .wrap()
            .query_balance(&Addr::unchecked("user"), "eth")
            .unwrap()
            .amount
            .u128();
        assert_eq!(balance, 5);
    }
}
```

**Comment by JohnScience** [comment]
I believe the documentation should be improved so that devs don't experience issues like this.

**Comment by DariuszDepta** [comment]
Hi @JohnScience, you are right!
The documentation should be improved and now we are working on it.
Your last example is the right approach to use Bech32 addresses since version 0.19.0 of **MultiTest**.
The initial article was published here: [Addresses in CosmWasm MultiTest](https://medium.com/cosmwasm/addresses-in-cosmwasm-multitest-68207ae845e6) (some time ago). There are also multiple tests in **MultTest** that show how to use Bech32 addresses. But we work on documentation improvements now.

**Thanks again for your help and exhaustive examples!**

I'm closing this issue, but it's linked to the overall documentation improvement task, so we don't forget about it.
